'use strict';
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const STORAGE={profile:'psicoandino.story.profile.v1',characters:'psicoandino.story.characters.v1',expeditions:'psicoandino.story.expeditions.v1'};
const FIGURES=['triangle','circle','square','line'];const COLORS=['#b78627','#c73a4a','#6d7c50','#248692'];
const STAT_KEYS=['speed','recovery','force','cadence','mobility'];const ALLOCATABLE_STAT_KEYS=['recovery','force','cadence','mobility'];const STAT_LABELS={speed:'Laser physics',recovery:'Recovery',force:'Force',cadence:'Cadence',mobility:'Mobility'};const BASE_STATS={speed:1,recovery:1,force:1,cadence:1,mobility:1};const DEFAULT_LASER_SPEED=10;
const ENEMY_NAMES=['LUMEN','BRUMA','NODO','CENIZA','RITMO','UMBRA','VECTOR','PULSO','MATERIA','ECO'];
const DUNGEONS=[
{id:'root-forest',name:'ROOT FOREST',figure:'line',color:'#6d7c50',x:22,y:28,climate:'Living underground',signature:'Roots · spores · memory',seed:'root'},
{id:'copper-cavern',name:'COPPER CAVERN',figure:'circle',color:'#248692',x:77,y:24,climate:'Mineral resonance',signature:'Water · ore · echoes',seed:'copper'},
{id:'lumen-tower',name:'LUMEN TOWER',figure:'triangle',color:'#b78627',x:78,y:74,climate:'Vertical knowledge',signature:'Light · mechanisms · ascent',seed:'lumen'},
{id:'sunken-coast',name:'SUNKEN COAST',figure:'square',color:'#c73a4a',x:23,y:76,climate:'Submerged ruins',signature:'Salt · tide · warning',seed:'coast'}
];
let selectedDungeonId=null;
const SCREENS=['home','user','character','worldMap','story','battle','floorSummary','expeditionSummary','history'];
const load=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const uid=()=>Math.random().toString(36).slice(2)+Date.now().toString(36);const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function show(id){SCREENS.forEach(s=>$('#'+s).classList.toggle('active',s===id));window.scrollTo(0,0)}
let profile=load(STORAGE.profile,{username:''});let characters=load(STORAGE.characters,[]);let selectedCharacterId=characters[0]?.id||null;let draft={id:null,name:'New character',figure:'triangle',color:'#b78627',stats:{...BASE_STATS}};let expedition=null;let battle=null;let liveTest=null;let liveTestCells=[];let liveEvents=[];let frameId=0;
let externalFloorCompleteHandler=null;

function ensureProfile(){if(!profile.username){$('#usernameInput').value='';show('user');return false}return true}
function pointsAssigned(stats=draft.stats){return STAT_KEYS.reduce((s,k)=>s+(stats[k]||0),0)}
function normalizeLockedSpeed(stats){const out={...BASE_STATS,...stats};const originalTotal=STAT_KEYS.reduce((sum,key)=>sum+(Number(out[key])||0),0);out.speed=1;let diff=originalTotal-STAT_KEYS.reduce((sum,key)=>sum+(Number(out[key])||0),0);const order=['force','cadence','mobility','recovery'];while(diff>0){let moved=false;for(const key of order){if(out[key]<5){out[key]++;diff--;moved=true;if(diff===0)break}}if(!moved)break}while(diff<0){let moved=false;for(const key of [...order].reverse()){if(out[key]>0){out[key]--;diff++;moved=true;if(diff===0)break}}if(!moved)break}return out}
function configFromStats(stats){return {spacesPerSecond:DEFAULT_LASER_SPEED,hitRecoveryMs:[1600,1250,950,700,450,250][stats.recovery],damage:[1,2,3,5,8,13][stats.force],fireCooldownMs:[1500,1100,800,550,350,180][stats.cadence],moveCooldownMs:[420,330,250,180,120,80][stats.mobility]}}
function buildStats(){const root=$('#stats');root.innerHTML='';STAT_KEYS.forEach(key=>{const row=document.createElement('div');row.className='stat-row';const locked=key==='speed';row.innerHTML=`<span>${STAT_LABELS[key]}${locked?' · DEFAULT':''}</span><button data-key="${key}" data-delta="-1" ${locked?'disabled':''}>−</button><span class="stat-value">${locked?DEFAULT_LASER_SPEED:draft.stats[key]}</span><button data-key="${key}" data-delta="1" ${locked?'disabled':''}>+</button>`;root.append(row)});$('#assignedPoints').textContent=pointsAssigned();syncLiveTestDraft()}
function updatePreview(){draft.name=$('#characterName').value.trim()||'Unnamed';draft.figure=$('#characterFigure').value;draft.color=$('#characterColor').value;const p=$('#characterPreview');p.dataset.figure=draft.figure;p.style.setProperty('--figure-color',draft.color);syncLiveTestDraft()}
function openCharacter(c=null){draft=c?structuredClone(c):{id:null,name:'New character',figure:'triangle',color:'#b78627',stats:{...BASE_STATS}};draft.stats=normalizeLockedSpeed(draft.stats);$('#characterName').value=draft.name;$('#characterFigure').value=draft.figure;$('#characterColor').value=draft.color;buildStats();updatePreview();show('character');resetLiveTest()}
function saveCharacter(){updatePreview();if(pointsAssigned()!==5)return alert('Exactly 5 points must be assigned.');if(!draft.id)draft.id=uid();const existing=characters.findIndex(c=>c.id===draft.id);if(existing>=0)characters[existing]=structuredClone(draft);else characters.push(structuredClone(draft));selectedCharacterId=draft.id;save(STORAGE.characters,characters);renderHome();show('home')}
function buildLiveTestArena(){const root=$('#liveTestArena');if(!root)return;root.innerHTML='';liveTestCells=[];for(let r=0;r<3;r++)for(let c=0;c<6;c++){const el=document.createElement('div');el.className='cell'+(c>=3?' enemy-zone':'');root.append(el);liveTestCells.push(el)}}
function liveCellAt(r,c){return liveTestCells[r*6+c]}
function pushLiveEvent(label,now=performance.now()){liveEvents.unshift({label,elapsed:liveTest?Math.max(0,(now-liveTest.startedAt)/1000):0});liveEvents=liveEvents.slice(0,24)}
function resetLiveTest(){if(!$('#liveTestArena'))return;const now=performance.now();liveEvents=[];liveTest={startedAt:now,player:{name:draft.name,figure:draft.figure,color:draft.color,row:1,col:1,config:configFromStats(draft.stats),lastMoveAt:-Infinity},totem:{name:'TOTEM',figure:'square',color:'#248692',row:1,col:4,life:30,maxLife:30},lasers:[],nextLaserId:1,lastShotAt:-Infinity,shots:0,hits:0,mode:'ACTIVE'};buildLiveTestArena();pushLiveEvent('Totem reset',now);renderLiveTest(now)}
function syncLiveTestDraft(){if(!liveTest)return;liveTest.player.name=draft.name;liveTest.player.figure=draft.figure;liveTest.player.color=draft.color;liveTest.player.config=configFromStats(draft.stats)}
function moveLiveTest(dr,dc,now=performance.now()){if(!liveTest||liveTest.mode!=='ACTIVE')return;const p=liveTest.player;if(now-p.lastMoveAt<p.config.moveCooldownMs)return;const nr=p.row+dr,nc=p.col+dc;if(nr<0||nr>2||nc<0||nc>2)return;p.row=nr;p.col=nc;p.lastMoveAt=now}
function fireLiveTest(now=performance.now()){if(!liveTest||liveTest.mode!=='ACTIVE'||now-liveTest.lastShotAt<liveTest.player.config.fireCooldownMs)return;liveTest.lastShotAt=now;liveTest.shots++;pushLiveEvent('Shot fired',now);liveTest.lasers.push({id:liveTest.nextLaserId++,row:liveTest.player.row,col:liveTest.player.col+1,speed:liveTest.player.config.spacesPerSecond,nextStepAt:now+1000/liveTest.player.config.spacesPerSecond,active:true})}
function updateLiveTest(now){if(!liveTest||liveTest.mode!=='ACTIVE')return;for(const l of liveTest.lasers){while(l.active&&now>=l.nextStepAt){l.col++;l.nextStepAt+=1000/l.speed;if(l.col>5){l.active=false;break}if(l.row===liveTest.totem.row&&l.col===liveTest.totem.col){liveTest.totem.life=Math.max(0,liveTest.totem.life-liveTest.player.config.damage);liveTest.hits++;pushLiveEvent(`Hit · ${liveTest.player.config.damage} damage`,now);l.active=false;if(liveTest.totem.life===0){liveTest.mode='ENDED';pushLiveEvent('Totem destroyed',now)}}}}liveTest.lasers=liveTest.lasers.filter(l=>l.active)}
function renderLiveTest(now=performance.now()){if(!liveTest||!liveTestCells.length)return;liveTestCells.forEach(c=>c.replaceChildren());liveCellAt(liveTest.player.row,liveTest.player.col).append(renderEntity(liveTest.player));liveCellAt(liveTest.totem.row,liveTest.totem.col).append(renderEntity(liveTest.totem));liveTest.lasers.forEach(l=>{const el=document.createElement('div');el.className='laser';liveCellAt(l.row,l.col)?.append(el)});$('#liveTotemHp').textContent=liveTest.totem.life;$('#liveTestTime').textContent=((now-liveTest.startedAt)/1000).toFixed(1)+' s';$('#liveTestShots').textContent=liveTest.shots;$('#liveTestAccuracy').textContent=pct(liveTest.hits,liveTest.shots);const cd=liveTest.player.config.fireCooldownMs,load=cd?clamp((now-liveTest.lastShotAt)/cd*100,0,100):100;$('#liveCooldownFill').style.width=load+'%';$('#liveCooldownPercent').textContent=Math.round(load)+'%';renderLiveEvidence()}
function renderLiveEvidence(){if(!liveTest)return;const c=liveTest.player.config,accuracy=liveTest.shots?liveTest.hits/liveTest.shots*100:0,progress=(1-liveTest.totem.life/liveTest.totem.maxLife)*100;$('#evidenceDamage').textContent=c.damage;$('#evidenceCadence').textContent=Math.round(c.fireCooldownMs)+' ms';$('#evidenceSpeed').textContent=c.spacesPerSecond.toFixed(1)+' cells/s';$('#evidenceMobility').textContent=Math.round(c.moveCooldownMs)+' ms';$('#evidenceHitsToDestroy').textContent=Math.ceil(liveTest.totem.maxLife/c.damage);$('#evidenceAccuracy').textContent=accuracy.toFixed(1)+'%';$('#evidenceAccuracyBar').style.width=clamp(accuracy,0,100)+'%';$('#evidenceProgress').textContent=Math.round(progress)+'%';$('#evidenceProgressBar').style.width=clamp(progress,0,100)+'%';$('#liveEventLog').innerHTML=liveEvents.map(e=>`<div><time>${e.elapsed.toFixed(1)}s</time>${e.label}</div>`).join('')||'<div class="muted">No events yet.</div>'}
function beginTotemTest(){updatePreview();if(pointsAssigned()!==5)return alert('Exactly 5 points must be assigned before testing.');const testCharacter=structuredClone(draft),pc=configFromStats(testCharacter.stats),now=performance.now();const totemDifficulty={score:0,aggression:0,mobility:0,evasion:0,pressure:0,resilience:20};battle={kind:'TOTEM_TEST',startedAt:now,player:{...testCharacter,row:1,col:1,hitCount:0,config:pc,lastMoveAt:-Infinity,lastHitAt:-Infinity},enemy:{id:'totem',name:'TOTEM',figure:'square',color:'#248692',stats:{...BASE_STATS},difficulty:totemDifficulty,row:1,col:4,life:30,maxLife:30,config:configFromStats(BASE_STATS),lastMoveAt:now,lastFireAt:now},lasers:[],nextLaserId:1,lastShotAt:-Infinity,shots:0,hits:0,hitsReceived:0,mode:'ACTIVE'};buildArena();renderBattle();show('battle')}
function leaveTotemTest(){battle=null;show('character');buildStats();updatePreview()}
function renderHome(){profile=load(STORAGE.profile,{username:''});characters=load(STORAGE.characters,[]);$('#homeUsername').textContent=profile.username||'UNSET';const selected=characters.find(c=>c.id===selectedCharacterId)||characters[0]||null;if(selected)selectedCharacterId=selected.id;const roster=$('#roster');roster.innerHTML='';if(!characters.length)roster.innerHTML='<div class="empty">No characters created.</div>';characters.forEach(c=>{const item=document.createElement('div');item.className='roster-item'+(c.id===selectedCharacterId?' active':'');item.innerHTML=`<span class="swatch" style="--swatch:${c.color}"></span><div><strong>${c.name}</strong><div class="muted">${c.figure} · ${STAT_KEYS.map(k=>c.stats[k]).join('/')}</div></div><div class="toolbar"><button class="btn" data-select="${c.id}">Select</button><button class="btn" data-edit="${c.id}">Edit</button></div>`;roster.append(item)});$('#startStory').disabled=!selectedCharacterId||!profile.username;const exps=load(STORAGE.expeditions,[]);const completed=exps.filter(e=>e.status==='COMPLETED');const battles=exps.flatMap(e=>e.floors||[]).flatMap(f=>f.encounters||[]);$('#profileSummary').innerHTML=`<div class="metric-grid"><div class="metric"><span>Username</span><strong>${profile.username||'Unset'}</strong></div><div class="metric"><span>Characters</span><strong>${characters.length}</strong></div><div class="metric"><span>Expeditions</span><strong>${exps.length}</strong></div><div class="metric"><span>Encounters</span><strong>${battles.length}</strong></div></div>`;const recent=$('#recentExpeditions');recent.innerHTML='';if(!exps.length)recent.innerHTML='<div class="empty">No expeditions registered.</div>';else recent.innerHTML=tableHTML(['Status','Character','Floors','Duration','Started'],exps.slice().reverse().slice(0,6).map(e=>[e.status,e.characterName,`${e.completedFloors||0}/11`,fmtSec(e.totalDurationSeconds||0),new Date(e.createdAt).toLocaleString()]));}
function tableHTML(headers,rows){return `<div style="overflow:auto"><table class="history-table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function hashSeed(str){let h=2166136261;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}function rng(seed){let a=seed>>>0;return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function revealAround(f,cx,cy,radius=4){if(!f.discovered)f.discovered=new Set();for(let y=Math.max(0,cy-radius);y<=Math.min(f.H-1,cy+radius);y++)for(let x=Math.max(0,cx-radius);x<=Math.min(f.W-1,cx+radius);x++){const dx=x-cx,dy=y-cy;if(dx*dx+dy*dy<=radius*radius)f.discovered.add(`${x},${y}`)}}
function generateFloor(expSeed,floor){const r=rng(hashSeed(`${expSeed}:${floor}:v1`));const W=100,H=100;const tiles=new Uint8Array(W*H);const rooms=[];for(let i=0;i<22;i++){const w=5+Math.floor(r()*10),h=5+Math.floor(r()*8),x=2+Math.floor(r()*(W-w-4)),y=2+Math.floor(r()*(H-h-4));rooms.push({x,y,w,h,cx:x+Math.floor(w/2),cy:y+Math.floor(h/2)});for(let yy=y;yy<y+h;yy++)for(let xx=x;xx<x+w;xx++)tiles[yy*W+xx]=1}for(let i=1;i<rooms.length;i++){let a=rooms[i-1],b=rooms[i];for(let x=Math.min(a.cx,b.cx);x<=Math.max(a.cx,b.cx);x++)tiles[a.cy*W+x]=1;for(let y=Math.min(a.cy,b.cy);y<=Math.max(a.cy,b.cy);y++)tiles[y*W+b.cx]=1}const start={x:rooms[0].cx,y:rooms[0].cy},exit={x:rooms.at(-1).cx,y:rooms.at(-1).cy};const enemyCount=3+floor;const occupied=new Set([`${start.x},${start.y}`,`${exit.x},${exit.y}`]);const enemies=[];for(let i=0;i<enemyCount;i++){let x,y,k;do{x=Math.floor(r()*W);y=Math.floor(r()*H);k=`${x},${y}`}while(!tiles[y*W+x]||occupied.has(k));occupied.add(k);enemies.push(generateEnemy(floor,r,x,y))}const discovered=new Set();revealAround({W,H,tiles,discovered},start.x,start.y);return {W,H,tiles,start,exit,enemies,visited:new Set([`${start.x},${start.y}`]),discovered,steps:0,encounters:[],startedAt:performance.now(),elapsedBefore:0}}
function difficultyComponents(floor,r,stats){const aggression=clamp(8+floor*6+Math.round(r()*18),0,100);const mobility=clamp(10+floor*5+stats.mobility*7+Math.round(r()*12),0,100);const evasion=clamp(floor*6+stats.recovery*8+Math.round(r()*15),0,100);const pressure=clamp(6+floor*7+stats.cadence*6+Math.round(r()*15),0,100);const resilience=clamp(10+floor*5+stats.recovery*7+Math.round(r()*12),0,100);const score=Math.round(aggression*.24+mobility*.18+evasion*.18+pressure*.24+resilience*.16);return {score,aggression,mobility,evasion,pressure,resilience}}
function difficultyLabel(score){if(score<20)return'LOW';if(score<40)return'GUARDED';if(score<60)return'ACTIVE';if(score<80)return'SEVERE';return'EXTREME'}
function generateEnemy(floor,r,x,y){const stats={speed:1};let remain=4;ALLOCATABLE_STAT_KEYS.forEach((k,i)=>{const v=i===ALLOCATABLE_STAT_KEYS.length-1?remain:Math.floor(r()*(remain+1));stats[k]=v;remain-=v});const d=difficultyComponents(floor,r,stats);return{id:uid(),name:`${ENEMY_NAMES[Math.floor(r()*ENEMY_NAMES.length)]}-${String(Math.floor(r()*100)).padStart(2,'0')}`,figure:FIGURES[Math.floor(r()*FIGURES.length)],color:COLORS[Math.floor(r()*COLORS.length)],stats,x,y,difficulty:d}}
function startExpedition(){if(!ensureProfile())return;const c=characters.find(c=>c.id===selectedCharacterId);if(!c)return;expedition={id:uid(),status:'ROUTING',createdAt:new Date().toISOString(),usernameSnapshot:profile.username,characterId:c.id,characterName:c.name,character:structuredClone(c),currentFloor:0,completedFloors:0,totalDurationSeconds:0,totalSteps:0,totalHitsReceived:0,totalShots:0,totalHitsDealt:0,floors:[]};selectedDungeonId=null;renderWorldMap();show('worldMap')}
function renderWorldMap(){const canvas=$('#worldMapCanvas');if(!canvas||!expedition)return;$('#mapCharacterName').textContent=expedition.characterName;canvas.querySelectorAll('.world-node,.world-route').forEach(n=>n.remove());DUNGEONS.forEach(d=>{const dx=d.x-50,dy=d.y-50;const len=Math.hypot(dx,dy);const angle=Math.atan2(dy,dx)*180/Math.PI;const route=document.createElement('i');route.className='world-route';route.style.left='50%';route.style.top='50%';route.style.width=len+'%';route.style.transform=`rotate(${angle}deg)`;canvas.append(route);const b=document.createElement('button');b.className='world-node'+(selectedDungeonId===d.id?' selected':'');b.dataset.dungeon=d.id;b.dataset.figure=d.figure;b.style.left=d.x+'%';b.style.top=d.y+'%';b.style.setProperty('--node-color',d.color);b.innerHTML=`<i class="node-glyph"></i><strong>${d.name}</strong><small>${d.climate}</small>`;canvas.append(b)});renderDungeonSelection()}
function renderDungeonSelection(){const d=DUNGEONS.find(x=>x.id===selectedDungeonId);$('#enterDungeon').disabled=!d;if(!d){$('#mapDungeonName').textContent='Select a dungeon';$('#mapDungeonDescription').textContent='The map routes the persistent profile and selected character into one procedural interior.';$('#mapDungeonMeta').innerHTML='';return}const g=$('#mapDungeonGlyph');g.dataset.figure=d.figure;g.style.setProperty('--figure-color',d.color);$('#mapDungeonName').textContent=d.name;$('#mapDungeonDescription').textContent=d.signature;$('#mapDungeonMeta').innerHTML=metricsHTML([['Depth','11 floors'],['Interior','100 × 100'],['Battle','3 × 6'],['State','Available']])}
function enterSelectedDungeon(){const d=DUNGEONS.find(x=>x.id===selectedDungeonId);if(!d||!expedition)return;expedition.status='ACTIVE';expedition.dungeonId=d.id;expedition.dungeonName=d.name;expedition.seed=`${profile.username}-${expedition.characterId}-${d.seed}-${Date.now()}`;expedition.currentFloor=0;expedition.floorState=generateFloor(expedition.seed,0);saveActive();renderStory();show('story')}
function saveActive(){if(!expedition?.floorState)return;sessionStorage.setItem('psicoandino.story.active',JSON.stringify({...expedition,floorState:serializeFloor(expedition.floorState)}))}
function serializeFloor(f){return {...f,elapsedBefore:floorElapsed(),startedAt:0,tiles:Array.from(f.tiles),visited:[...f.visited],discovered:[...(f.discovered||[])]}}
function restoreActive(){const raw=sessionStorage.getItem('psicoandino.story.active');if(!raw)return false;try{const restored=JSON.parse(raw);if(restored.status!=='ACTIVE'||!restored.floorState)return false;const f=restored.floorState;f.tiles=Uint8Array.from(f.tiles||[]);f.visited=new Set(f.visited||[]);f.discovered=new Set(f.discovered||f.visited||[]);f.elapsedBefore=Number(f.elapsedBefore)||0;f.startedAt=performance.now();expedition=restored;selectedCharacterId=restored.characterId||selectedCharacterId;renderStory();show('story');return true}catch(error){console.error('Active expedition restore failed',error);sessionStorage.removeItem('psicoandino.story.active');return false}}
function floorElapsed(){return expedition.floorState.elapsedBefore+(performance.now()-expedition.floorState.startedAt)/1000}
function renderStory(){const f=expedition.floorState;$('#expeditionCode').textContent=`${expedition.dungeonName||'DUNGEON'} · ${expedition.id.slice(0,8).toUpperCase()}`;$('#floorNumber').textContent=expedition.currentFloor;$('#floorEnemies').textContent=f.enemies.length;$('#floorSteps').textContent=f.steps;$('#floorEncounters').textContent=f.encounters.length;$('#floorHits').textContent=f.encounters.reduce((s,e)=>s+e.hitsReceived,0);renderViewport();renderMinimap()}
function renderViewport(){const f=expedition.floorState,c=expedition.character;const root=$('#viewport');root.innerHTML='';const vw=15,vh=11;for(let oy=-5;oy<=5;oy++)for(let ox=-7;ox<=7;ox++){const x=f.player?.x??f.start.x,y=f.player?.y??f.start.y;const tx=x+ox,ty=y+oy;const el=document.createElement('div');const isFloor=tx>=0&&ty>=0&&tx<f.W&&ty<f.H&&f.tiles[ty*f.W+tx];el.className='tile '+(isFloor?'floor':'wall');if(tx===f.exit.x&&ty===f.exit.y)el.className='tile exit';const enemy=f.enemies.find(e=>e.x===tx&&e.y===ty);if(enemy){el.classList.add('enemy');el.dataset.figure=enemy.figure;el.style.setProperty('--entity-color',enemy.color)}if(tx===x&&ty===y){el.classList.remove('enemy');el.classList.add('player');el.dataset.figure=c.figure;el.style.setProperty('--entity-color',c.color)}root.append(el)}}
function renderMinimap(){const f=expedition.floorState;const root=$('#minimap');root.innerHTML='';if(!(f.discovered instanceof Set))f.discovered=new Set(f.discovered||f.visited||[]);for(let my=0;my<50;my++)for(let mx=0;mx<50;mx++){const el=document.createElement('div');const sx=mx*2,sy=my*2;const samples=[[sx,sy],[sx+1,sy],[sx,sy+1],[sx+1,sy+1]].filter(([x,y])=>x<f.W&&y<f.H);const known=samples.some(([x,y])=>f.discovered.has(`${x},${y}`));const knownFloor=samples.some(([x,y])=>f.discovered.has(`${x},${y}`)&&f.tiles[y*f.W+x]);let cls='mini';if(known)cls+=knownFloor?' floor':' discovered-wall';if(samples.some(([x,y])=>f.visited.has(`${x},${y}`)))cls+=' visited';const p=f.player||f.start;if(Math.floor(p.x/2)===mx&&Math.floor(p.y/2)===my)cls+=' player';if(Math.floor(f.exit.x/2)===mx&&Math.floor(f.exit.y/2)===my)cls+=' exit';el.className=cls;root.append(el)}}
function moveStory(dx,dy){if(!expedition||battle)return;const f=expedition.floorState;if(!f.player)f.player={...f.start};const nx=f.player.x+dx,ny=f.player.y+dy;if(nx<0||ny<0||nx>=f.W||ny>=f.H||!f.tiles[ny*f.W+nx])return;f.player={x:nx,y:ny};f.steps++;f.visited.add(`${nx},${ny}`);revealAround(f,nx,ny);const enemy=f.enemies.find(e=>e.x===nx&&e.y===ny);if(enemy){beginBattle(enemy);return}if(nx===f.exit.x&&ny===f.exit.y&&f.enemies.length===0){completeFloor();return}renderStory();saveActive()}
function beginBattle(enemy){const pc=configFromStats(expedition.character.stats),ec=configFromStats(enemy.stats),now=performance.now();const score=enemy.difficulty.score;battle={kind:'STORY',startedAt:now,player:{...structuredClone(expedition.character),row:1,col:1,hitCount:0,config:pc,lastMoveAt:-Infinity,lastHitAt:-Infinity},enemy:{...structuredClone(enemy),row:1,col:4,life:10+Math.round(score*.5),maxLife:10+Math.round(score*.5),config:ec,lastMoveAt:now,lastFireAt:now},lasers:[],nextLaserId:1,lastShotAt:-Infinity,shots:0,hits:0,hitsReceived:0,mode:'ACTIVE'};buildArena();renderBattle();show('battle')}
const cells=[];function buildArena(){const root=$('#arena');root.innerHTML='';cells.length=0;for(let r=0;r<3;r++)for(let c=0;c<6;c++){const el=document.createElement('div');el.className='cell'+(c>=3?' enemy-zone':'');root.append(el);cells.push(el)}}function cellAt(r,c){return cells[r*6+c]}
function movePlayer(dr,dc,now=performance.now()){if(!battle||battle.mode!=='ACTIVE')return;const p=battle.player;if(now-p.lastMoveAt<p.config.moveCooldownMs)return;const nr=p.row+dr,nc=p.col+dc;if(nr<0||nr>2||nc<0||nc>2)return;p.row=nr;p.col=nc;p.lastMoveAt=now}
function fire(now=performance.now()){if(!battle||battle.mode!=='ACTIVE'||now-battle.lastShotAt<battle.player.config.fireCooldownMs)return;battle.lastShotAt=now;battle.shots++;battle.lasers.push({id:battle.nextLaserId++,owner:'player',row:battle.player.row,col:battle.player.col+1,direction:1,speed:battle.player.config.spacesPerSecond,nextStepAt:now+1000/battle.player.config.spacesPerSecond,active:true})}
function updateEnemy(now){const e=battle.enemy,d=e.difficulty;if(now-e.lastMoveAt>clamp(1200-d.mobility*9,180,1200)){e.lastMoveAt=now;let target=battle.player.row;if(d.evasion>55&&battle.lasers.some(l=>l.owner==='player'&&l.row===e.row&&l.col<e.col))target=[0,1,2].filter(r=>r!==e.row)[Math.floor(Math.random()*2)];e.row+=Math.sign(target-e.row);if(d.mobility>70&&Math.random()<.35)e.col=clamp(e.col+(Math.random()<.5?-1:1),3,5)}if(now-e.lastFireAt>clamp(1900-d.pressure*15,260,1900)){e.lastFireAt=now;const burst=d.aggression>80?3:d.aggression>55?2:1;for(let i=0;i<burst;i++)battle.lasers.push({id:battle.nextLaserId++,owner:'enemy',row:clamp(e.row+(i%2?1:0),0,2),col:e.col-1,direction:-1,speed:DEFAULT_LASER_SPEED,nextStepAt:now+1000/DEFAULT_LASER_SPEED+i*110,active:true})}}
function updateLasers(now){for(const l of battle.lasers){while(l.active&&now>=l.nextStepAt){l.col+=l.direction;l.nextStepAt+=1000/l.speed;if(l.col<0||l.col>5){l.active=false;break}if(l.owner==='player'&&l.row===battle.enemy.row&&l.col===battle.enemy.col){battle.enemy.life=Math.max(0,battle.enemy.life-battle.player.config.damage);battle.hits++;l.active=false;if(battle.enemy.life===0){finishBattle();return}}else if(l.owner==='enemy'&&l.row===battle.player.row&&l.col===battle.player.col){l.active=false;if(now-battle.player.lastHitAt>=battle.player.config.hitRecoveryMs){battle.player.lastHitAt=now;battle.player.hitCount++;battle.hitsReceived++}}}}battle.lasers=battle.lasers.filter(l=>l.active)}
function renderEntity(e){const el=document.createElement('div');el.className='entity';el.dataset.figure=e.figure;el.style.setProperty('--entity-color',e.color);return el}
function renderBattle(now=performance.now()){if(!battle)return;cells.forEach(c=>c.replaceChildren());cellAt(battle.player.row,battle.player.col).append(renderEntity(battle.player));cellAt(battle.enemy.row,battle.enemy.col).append(renderEntity(battle.enemy));battle.lasers.forEach(l=>{const el=document.createElement('div');el.className='laser'+(l.owner==='enemy'?' enemy-shot':'');cellAt(l.row,l.col)?.append(el)});const isTest=battle.kind==='TOTEM_TEST';$('#battleContextLabel').textContent=isTest?'CHARACTER SIMULATION · TOTEM':'ENCOUNTER · FLOOR';$('#battleFloor').textContent=isTest?'TEST':expedition.currentFloor;$('#exitBattleTest').classList.toggle('hidden',!isTest);$('#battlePlayerName').textContent=battle.player.name;$('#battleEnemyName').textContent=battle.enemy.name;$('#battleTime').textContent=((now-battle.startedAt)/1000).toFixed(1)+' s';$('#enemyHp').textContent=battle.enemy.life;$('#battleHitsReceived').textContent=battle.hitsReceived;$('#battleShots').textContent=battle.shots;$('#battleHitsDealt').textContent=battle.hits;const s=battle.enemy.difficulty.score;$('#difficultyScore').textContent=s;$('#difficultyLabel').textContent=difficultyLabel(s);$('#difficultyMarker').style.left=`calc(${s}% - 1px)`;const d=battle.enemy.difficulty;$('#difficultyExplanation').textContent=isTest?'Static calibration target. No movement, fire, tracking or evasion. Its only function is to expose the draft character’s movement, cadence and damage under the shared 10 cells/s laser physics.':`Aggression ${d.aggression}, mobility ${d.mobility}, evasion ${d.evasion}, pressure ${d.pressure}, resilience ${d.resilience}. Weighted into one constrained KPI.`;const cd=battle.player.config.fireCooldownMs,load=cd?clamp((now-battle.lastShotAt)/cd*100,0,100):100;$('#cooldownFill').style.width=load+'%';$('#cooldownPercent').textContent=Math.round(load)+'%'}
function finishBattle(){battle.mode='ENDED';const duration=(performance.now()-battle.startedAt)/1000;if(battle.kind==='TOTEM_TEST'){const shots=battle.shots,hits=battle.hits;alert(`Totem test complete. Duration ${duration.toFixed(1)} s · Shots ${shots} · Hits ${hits} · Accuracy ${shots?(hits/shots*100).toFixed(1):'0.0'}%.`);leaveTotemTest();return}const record={enemyId:battle.enemy.id,enemyName:battle.enemy.name,difficulty:battle.enemy.difficulty,durationSeconds:duration,shots:battle.shots,hitsDealt:battle.hits,hitsReceived:battle.hitsReceived};const f=expedition.floorState;f.encounters.push(record);f.enemies=f.enemies.filter(e=>e.id!==battle.enemy.id);expedition.totalHitsReceived+=record.hitsReceived;expedition.totalShots+=record.shots;expedition.totalHitsDealt+=record.hitsDealt;battle=null;show('story');renderStory();saveActive()}
function completeFloor(){
  if (externalFloorCompleteHandler) {
    externalFloorCompleteHandler();
    return;
  }
  const f=expedition.floorState;const duration=floorElapsed();const floorRecord={floor:expedition.currentFloor,durationSeconds:duration,steps:f.steps,encounters:f.encounters,enemyCount:f.encounters.length,avgDifficulty:avg(f.encounters.map(e=>e.difficulty.score)),hitsReceived:f.encounters.reduce((s,e)=>s+e.hitsReceived,0),shots:f.encounters.reduce((s,e)=>s+e.shots,0),hitsDealt:f.encounters.reduce((s,e)=>s+e.hitsDealt,0)};expedition.floors.push(floorRecord);expedition.completedFloors++;expedition.totalDurationSeconds+=duration;expedition.totalSteps+=f.steps;renderFloorSummary(floorRecord);show('floorSummary')
}
function renderFloorSummary(r){$('#floorSummaryText').textContent=`${expedition.characterName} completed floor ${r.floor}. The floor state and all encounters are now part of the expedition record.`;$('#floorSummaryMetrics').innerHTML=metricsHTML([['Duration',fmtSec(r.durationSeconds)],['Steps',r.steps],['Encounters',r.encounters.length],['Avg difficulty',r.avgDifficulty.toFixed(1)],['Hits received',r.hitsReceived],['Shots',r.shots],['Hits dealt',r.hitsDealt],['Accuracy',pct(r.hitsDealt,r.shots)]]);$('#floorEncounterTable').innerHTML=r.encounters.length?tableHTML(['Enemy','Difficulty','Duration','Shots','Dealt','Received'],r.encounters.map(e=>[e.enemyName,e.difficulty.score,fmtSec(e.durationSeconds),e.shots,e.hitsDealt,e.hitsReceived])):'<div class="empty">No encounters.</div>';$('#nextFloor').textContent=r.floor>=10?'Complete expedition':'Next floor'}
function nextFloor(){if(expedition.currentFloor>=10){completeExpedition();return}expedition.currentFloor++;expedition.floorState=generateFloor(expedition.seed,expedition.currentFloor);saveActive();renderStory();show('story')}
function completeExpedition(){expedition.status='COMPLETED';expedition.completedAt=new Date().toISOString();delete expedition.floorState;const exps=load(STORAGE.expeditions,[]);exps.push(structuredClone(expedition));save(STORAGE.expeditions,exps);sessionStorage.removeItem('psicoandino.story.active');renderExpeditionSummary(expedition);show('expeditionSummary')}
function metricsHTML(items){return items.map(([a,b])=>`<div class="metric"><span>${a}</span><strong>${b}</strong></div>`).join('')}
function avg(a){return a.length?a.reduce((s,v)=>s+v,0)/a.length:0}function pct(a,b){return b?`${(a/b*100).toFixed(1)}%`:'0.0%'}function fmtSec(s){const m=Math.floor(s/60),sec=(s%60).toFixed(1);return m?`${m}m ${sec}s`:`${sec}s`}
function renderExpeditionSummary(e){const encounters=e.floors.flatMap(f=>f.encounters);const avgDiff=avg(encounters.map(x=>x.difficulty.score));$('#expeditionHeadline').textContent=`${e.usernameSnapshot} completed floors 0–10 with ${e.characterName}. The entire expedition is registered in local history.`;$('#expeditionMetrics').innerHTML=metricsHTML([['Floors',e.completedFloors],['Total time',fmtSec(e.totalDurationSeconds)],['Steps',e.totalSteps],['Encounters',encounters.length],['Avg difficulty',avgDiff.toFixed(1)],['Hits received',e.totalHitsReceived],['Accuracy',pct(e.totalHitsDealt,e.totalShots)],['Efficiency',e.totalSteps?((encounters.length/e.totalSteps)*1000).toFixed(2)+'/1k steps':'0']]);drawLineChart($('#difficultyChart'),e.floors.map(f=>({x:f.floor,y:f.avgDifficulty})),0,100,'Difficulty');drawLineChart($('#durationChart'),e.floors.map(f=>({x:f.floor,y:f.durationSeconds})),0,Math.max(1,...e.floors.map(f=>f.durationSeconds)),'Seconds');$('#expeditionFloorTable').innerHTML=tableHTML(['Floor','Duration','Steps','Encounters','Avg KPI','Received','Accuracy'],e.floors.map(f=>[f.floor,fmtSec(f.durationSeconds),f.steps,f.encounters.length,f.avgDifficulty.toFixed(1),f.hitsReceived,pct(f.hitsDealt,f.shots)]))}
function drawLineChart(svg,data,min,max,label){const W=700,H=240,p=36;const pts=data.map((d,i)=>{const plotX=p+(W-2*p)*(i/Math.max(1,data.length-1));const plotY=H-p-(H-2*p)*((d.y-min)/Math.max(.001,max-min));return{plotX,plotY,domainX:d.x,value:d.y}});svg.innerHTML=`<line x1="${p}" y1="${H-p}" x2="${W-p}" y2="${H-p}" stroke="#264a80"/><line x1="${p}" y1="${p}" x2="${p}" y2="${H-p}" stroke="#264a80"/><polyline fill="none" stroke="#248692" stroke-width="4" points="${pts.map(q=>`${q.plotX},${q.plotY}`).join(' ')}"/>${pts.map(q=>`<circle cx="${q.plotX}" cy="${q.plotY}" r="5" fill="#f5f3ec"><title>Floor ${q.domainX}: ${q.value}</title></circle><text x="${q.plotX}" y="${H-12}" text-anchor="middle" fill="#9fb0c7" font-size="11">${q.domainX}</text>`).join('')}<text x="14" y="20" fill="#9fb0c7" font-size="12">${label}</text>`}
function renderHistory(){const exps=load(STORAGE.expeditions,[]),enc=exps.flatMap(e=>e.floors||[]).flatMap(f=>f.encounters||[]);$('#historyOverview').innerHTML=metricsHTML([['Username',profile.username||'Unset'],['Characters',characters.length],['Expeditions',exps.length],['Completed',exps.filter(e=>e.status==='COMPLETED').length],['Floors',exps.reduce((s,e)=>s+(e.completedFloors||0),0)],['Encounters',enc.length],['Avg difficulty',avg(enc.map(x=>x.difficulty.score)).toFixed(1)],['Hits received',exps.reduce((s,e)=>s+(e.totalHitsReceived||0),0)]]);$('#historyExpeditions').innerHTML=exps.length?tableHTML(['Date','User snapshot','Character','Status','Floors','Time','Hits'],exps.slice().reverse().map(e=>[new Date(e.createdAt).toLocaleString(),e.usernameSnapshot,e.characterName,e.status,e.completedFloors||0,fmtSec(e.totalDurationSeconds||0),e.totalHitsReceived||0])):'<div class="empty">No expeditions.</div>';$('#historyCharacters').innerHTML=characters.length?tableHTML(['Character','Figure','Stats','Current user'],characters.map(c=>[c.name,c.figure,STAT_KEYS.map(k=>c.stats[k]).join('/'),profile.username])):'<div class="empty">No characters.</div>'}
function loop(now){if(battle?.mode==='ACTIVE'){if(battle.kind==='STORY')updateEnemy(now);updateLasers(now);renderBattle(now)}if($('#character').classList.contains('active')&&liveTest){updateLiveTest(now);renderLiveTest(now)}if(expedition&&$('#story').classList.contains('active'))$('#floorTime').textContent=fmtSec(floorElapsed());frameId=requestAnimationFrame(loop)}
$('#editUser').onclick=()=>{$('#usernameInput').value=profile.username;show('user')};$('#saveUser').onclick=()=>{const v=$('#usernameInput').value.trim();if(!v)return alert('Username is required.');profile.username=v;save(STORAGE.profile,profile);renderHome();show('home')};$('#cancelUser').onclick=()=>show('home');$('#newCharacter').onclick=()=>openCharacter();$('#cancelCharacter').onclick=()=>show('home');$('#resetLiveTest').onclick=resetLiveTest;$('#saveCharacter').onclick=saveCharacter;$('#exitBattleTest').onclick=leaveTotemTest;$('#startStory').onclick=startExpedition;$('#openHistory').onclick=()=>{renderHistory();show('history')};$('#historyHome').onclick=()=>{renderHome();show('home')};$('#nextFloor').onclick=nextFloor;$('#floorHome').onclick=()=>{if(!confirm('Abandon the active expedition and return Home?'))return;expedition.status='ABANDONED';expedition.totalDurationSeconds+=expedition.floorState?floorElapsed():0;delete expedition.floorState;const exps=load(STORAGE.expeditions,[]);exps.push(structuredClone(expedition));save(STORAGE.expeditions,exps);sessionStorage.removeItem('psicoandino.story.active');expedition=null;renderHome();show('home')};$('#expeditionHome').onclick=()=>{expedition=null;renderHome();show('home')};$('#expeditionHistory').onclick=()=>{renderHistory();show('history')};$('#newExpeditionSame').onclick=startExpedition;$('#abandonExpedition').onclick=()=>{if(confirm('Abandon this expedition?')){expedition.status='ABANDONED';expedition.totalDurationSeconds+=(expedition.floorState?floorElapsed():0);delete expedition.floorState;const exps=load(STORAGE.expeditions,[]);exps.push(expedition);save(STORAGE.expeditions,exps);sessionStorage.removeItem('psicoandino.story.active');expedition=null;renderHome();show('home')}};
$('#roster').addEventListener('click',e=>{const s=e.target.dataset.select,ed=e.target.dataset.edit;if(s){selectedCharacterId=s;renderHome()}if(ed)openCharacter(characters.find(c=>c.id===ed))});$('#stats').addEventListener('click',e=>{const b=e.target.closest('button[data-key]');if(!b)return;const k=b.dataset.key;if(k==='speed')return;const d=Number(b.dataset.delta),n=draft.stats[k]+d;if(n<0||n>5)return;if(d>0&&pointsAssigned()>=5)return;draft.stats[k]=n;buildStats()});['characterName','characterFigure','characterColor'].forEach(id=>$('#'+id).addEventListener('input',updatePreview));
window.addEventListener('keydown',e=>{const k=e.key.toLowerCase(),map={arrowup:[0,-1],w:[0,-1],arrowdown:[0,1],s:[0,1],arrowleft:[-1,0],a:[-1,0],arrowright:[1,0],d:[1,0]},typing=['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName);if($('#character').classList.contains('active')&&!typing){const bmap={arrowup:[-1,0],w:[-1,0],arrowdown:[1,0],s:[1,0],arrowleft:[0,-1],a:[0,-1],arrowright:[0,1],d:[0,1]};if(k in bmap){e.preventDefault();moveLiveTest(...bmap[k])}else if(k===' '){e.preventDefault();fireLiveTest()}}else if($('#story').classList.contains('active')&&k in map){e.preventDefault();moveStory(...map[k])}else if($('#battle').classList.contains('active')){const bmap={arrowup:[-1,0],w:[-1,0],arrowdown:[1,0],s:[1,0],arrowleft:[0,-1],a:[0,-1],arrowright:[0,1],d:[0,1]};if(k in bmap){e.preventDefault();movePlayer(...bmap[k])}else if(k===' '){e.preventDefault();fire()}}});
$('#worldMapCanvas').addEventListener('click',e=>{const node=e.target.closest('[data-dungeon]');if(!node)return;selectedDungeonId=node.dataset.dungeon;renderWorldMap()});$('#enterDungeon').onclick=enterSelectedDungeon;$('#mapHome').onclick=()=>{expedition=null;renderHome();show('home')};

function stageAdapterStartDungeon(payload){
  console.log('[STORY] stageAdapterStartDungeon called with payload:', payload ? payload.id : null);
  expedition = payload;
  console.log('[STORY] expedition assigned to lexical binding');
  show('story');
  console.log('[STORY] story screen active');
  renderStory();
  console.log('[STORY] renderStory complete');
}
function stageAdapterGetRuntimeState(){
  return { expedition, battle };
}
function stageAdapterSetFloorCompleteHandler(handler){
  externalFloorCompleteHandler = handler;
}

window.PSICOANDINO_STORY_ADAPTER = {
  startDungeon: stageAdapterStartDungeon,
  getRuntimeState: stageAdapterGetRuntimeState,
  setFloorCompleteHandler: stageAdapterSetFloorCompleteHandler,
  generateFloor: generateFloor,
  show: show,
  renderStory: renderStory,
  completeFloor: completeFloor
};

renderHome();buildStats();updatePreview();buildLiveTestArena();resetLiveTest();const restored=profile.username&&restoreActive();if(!profile.username)show('user');else if(!restored)show('home');frameId=requestAnimationFrame(loop);
